### ISSUE TITLE
使用大会员cookie也无法解析出大会员支持的画质

### ISSUE THREAD

**Issue by Unreallyg** [A-Soul-Database/RangeDownloader#6]
使用大会员cookie也无法解析出大会员支持的画质。我使用了不同的大会员账号的cookie解析视频，但是和非大会员账号的cookie解析出的视频画质一样低，多次测试也没有解决，且大会员的cookie经过验证都是有效的。该问题这个月才出现，上个月仍能正常解析出高画质视频。

**Comment by P-PPPP** [comment]
收到

**Comment by P-PPPP** [comment]
已经修复
