### ISSUE TITLE
下载视频为360p

### ISSUE THREAD

**Issue by tuteng614** [A-Soul-Database/RangeDownloader#9]
您好，我哪怕设置了大会员cookies下载下来也是360p。

**Comment by P-PPPP** [comment]
抱歉GitHub推送导致我经常看不到消息。请你使用 `rd.asdb.live` 前端重新绑定一下cookies，若还无法下载请评论，感谢

**Comment by tuteng614** [comment]
现在使用`rd.asdb.live`可以下载最高画质了，谢谢！好奇是你前端那边做了什么调整吗？
